Vagrant.configure(2) do |config|
  config.vm.define "kernel update" do |srv|
    srv.vm.box = "centos8"
    srv.vm.synced_folder "./", "/vagrant"
    srv.vm.hostname = "centos8"
    srv.vm.network(:private_network, ip: "192.168.56.8")
    srv.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
    end
  end
end
